### ISSUE TITLE
[BUG]Command /hg kit has a little problem

### ISSUE THREAD

**Issue by Matthieu-Giaccaglia** [ShaneBeeStudios/HungerGames#3]
**Describe the bug**
When we are in game and waiting for start, command /hg kit doesn't show kit that can we use in chat. It's a minor bug. Sometimes the command works correctly, sometimes it doesn't. (sorry for my english)

**To Reproduce**
The bug happens when I use / hg forcestart because I do tests on my own. I don't know if this happens if the game starts normally.

**Expected behavior**
So I would like that when using / hg kit, the kits are displayed normally in place of the <not-in-game>.

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/60432056/80544675-d7258b00-89b1-11ea-9a0f-81ca878f6448.png)

**Version Info:**
 -  4.14.0
 - Spigot 1.14.4

**Comment by ShaneBeee** [comment]
which version of the beta are you using?

**Comment by Matthieu-Giaccaglia** [comment]
The version 8. Sorry i didn't notified that.

**Comment by ShaneBeee** [comment]
Okay thank you for letting me know. Ill get that fixed up :)

**Comment by Matthieu-Giaccaglia** [comment]
Your welcom, good luck !

**Comment by ShaneBeee** [comment]
Are you sure you're using beta 8?

I just did a test:
<img width="966" alt="Screen Shot 2020-04-28 at 4 44 43 PM" src="https://user-images.githubusercontent.com/20008482/80548368-a0c71c00-896f-11ea-8007-71fc83faae4d.png">

**Comment by Matthieu-Giaccaglia** [comment]
Yes, i use the .jar that you shared in Discord in channel hunger-games

![image](https://user-images.githubusercontent.com/60432056/80548677-bfeb9b00-89bb-11ea-9b98-832f9c7d1d9e.png)

**Comment by ShaneBeee** [comment]
Ok after a little investigating it seems to be an issue with `/hg reload` ... for now just restart your server and it should solve the issue.
I will attempt to fix this issue.

**Comment by Matthieu-Giaccaglia** [comment]
But i think it's because of the map that i use for the arena. I don't have any problem with my other arenas.
The arena that has the bug, has problem when i use /hg forcestart too, it says all time that the game is already running but it isn't. And i have to wait 5 seconde that for the command works.
I already restart my server and it's doesn't fix the problem. But it's okay, it's just the map of my arena that it has a problem, don't worry. Thanks for your help !

**Comment by ShaneBeee** [comment]
Hmm interesting.
I only came to the kit issue when I used `/hg reload` 
Someone else told me they're having an issue with 2 games running at once, probably an underlying issue I'm not seeing.

**Comment by Matthieu-Giaccaglia** [comment]
The bug is not very important. If Mojang hadn't added the command prediction we are writing, everything would be fine.

**Comment by ShaneBeee** [comment]
This should be fixed in the latest update 4.13.13
